# Change these first
owner: tmeuze # Your GitHub username
repo: uptime-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Gmail
    url: https://mail.google.com
  - name: GM GlobalConnect
    url: https://www.autopartners.net/gmentsso/UI/Login
  - name: FMCDealer
    url: https://www.faust.idp.ford.com/
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Authy
    method: GET
    url: https://gpkpyklzq55q.statuspage.io/api/v2/summary.json
    headers:
      - "Content-Type=application/json"
    body: '("name":"Authy 2FA","status":"operational")'
  - name: Authy 2
    method: GET
    url: https://gpkpyklzq55q.statuspage.io/api/v2/summary.json
    headers:
      - "Content-Type=application/json"
    expectedStatusCodes: 
      - '("name":"Authy 2FA","status":"operational")'

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: ups.andro.pw
  theme: dark
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor
  introTitle: Status Portal
  introMessage: 
#   navbar:
#     - title: Status
#       href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
